version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "17:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 10
  versioning-strategy: increase
  allow:
  - dependency-type: direct
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: ember-source
    versions:
    - 3.24.1
    - 3.25.0
    - 3.25.1
    - 3.25.2
    - 3.25.3
    - 3.26.0
  - dependency-name: ember-cli-htmlbars
    versions:
    - 5.3.1
    - 5.3.2
    - 5.4.0
    - 5.5.0
    - 5.6.0
    - 5.6.1
    - 5.6.2
    - 5.6.3
    - 5.6.4
    - 5.6.5
    - 5.7.0
  - dependency-name: ember-power-select
    versions:
    - 4.1.0
    - 4.1.2
    - 4.1.3
  - dependency-name: ember-basic-dropdown
    versions:
    - 3.0.12
    - 3.0.13
    - 3.0.14
    - 3.0.15
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "17:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 10
