name: Kitsu Test Suite
on:
  push:
  pull_request:
    # Branches from forks have the form 'user:branch-name' so we only run
    # this job on pull_request events for branches that look like fork
    # branches. Without this we would end up running this job twice for non
    # forked PRs, once for the push and then once for opening the PR.
    branches:
    - '**:**'

jobs:
  test:
    name: Node ${{ matrix.node_version}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [14]
        os: [ubuntu-latest]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Use Node ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}

    - name: Restore Cache
      uses: actions/cache@v2
      with:
        path: |
          node_modules
        key: ${{ matrix.os }}-${{ matrix.node_version }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: ${{ matrix.os }}-${{ matrix.node_version }}-yarn-

    - name: Install Dependencies
      run: yarn install --pure-lockfile

    - name: Test App
      run: COVERAGE=true yarn test:ci

    - name: Report Test Coverage
      if: github.event_name == 'push'
      uses: paambaati/codeclimate-action@v2.7.4
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        coverageLocations: |
          ${{ github.workspace }}/coverage/lcov.info:lcov

  crowdin:
    name: CrowdIn
    needs: [test]
    runs-on: ubuntu-latest
    if: github.ref != 'ref/heads/the-future'
    steps:
    - uses: actions/checkout@v2
    - name: Check Changes
      if: github.ref == 'ref/heads/crowdin'
      run: if !(git diff --summary --exit-code the-future...);then echo "HAS_CHANGES=true">>$GITHUB_ENV;else echo "HAS_CHANGES=false">>$GITHUB_ENV;fi
    - name: Auto Merge
      if: github.ref == 'ref/heads/crowdin' && env.HAS_CHANGES == 'true'
      uses: ridedott/merge-me-action@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MERGE_METHOD: SQUASH
